- name: Ensure git config dir exists
  file:
    path: "{{ home_directory }}/.config/git"
    state: directory

- name: Install dotfiles
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  loop:
    - src: config.j2
      dest: "{{ home_directory }}/.config/git/config"
    - src: ignore.j2
      dest: "{{ home_directory }}/.config/git/ignore"
    - src: hub.j2
      dest: "{{ home_directory }}/.config/hub"
